name: Build and Test
on: [push, pull_request]
jobs:
  Build-and-Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies of Python
      run: pip3 install -r testcases/requirements.txt
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: python3 testcases/test.py
    - name: Fetch the score
      # We've saved the score into `.score` file, from which we fetch the score again.
      id: score
      # We follow the palette of OJ (http://codeforces.com/problemset/status)
      # The badge is green if the score is full, blue otherwise.
      run: |
        echo "##[set-output name=data;]$(cat .score)"
        echo "##[set-output name=color;]$(score=$(cat .score) && [[ $score == '100.0' ]] && echo '0A0' || echo '00A')"
    - name: Score badge
      uses: RubbaBoy/BYOB@v1.3.0
      with:
        NAME: score
        LABEL: 'score'
        STATUS: ${{ steps.score.outputs.data }}
        COLOR: ${{ steps.score.outputs.color }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
